"""Initial schema

Revision ID: 3f596aa495bd
Revises:
Create Date: 2026-03-04
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3f596aa495bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_name'), ['name'], unique=True)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('draft_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_code', sa.String(length=12), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('player_a_ready', sa.Integer(), nullable=False),
    sa.Column('player_b_ready', sa.Integer(), nullable=False),
    sa.Column('coin_toss_winner', sa.String(length=10), nullable=True),
    sa.Column('toss_winner_choice', sa.String(length=15), nullable=True),
    sa.Column('first_pick_player', sa.String(length=10), nullable=True),
    sa.Column('first_half_player', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_a_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_b_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_sessions_room_code'), ['room_code'], unique=True)

    op.create_table('free_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'character_id', name='uq_free_char_season')
    )
    with op.batch_alter_table('free_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_characters_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_characters_season_id'), ['season_id'], unique=False)

    op.create_table('draft_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.Column('acting_player', sa.String(length=10), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['draft_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'character_id', name='uq_action_character'),
    sa.UniqueConstraint('session_id', 'sequence_num', name='uq_action_sequence')
    )
    with op.batch_alter_table('draft_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_actions_session_id'), ['session_id'], unique=False)

    op.create_table('team_building_swaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=10), nullable=False),
    sa.Column('original_char_id', sa.Integer(), nullable=False),
    sa.Column('free_char_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['free_char_id'], ['characters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_char_id'], ['characters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['draft_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'player', name='uq_swap_player_session')
    )
    with op.batch_alter_table('team_building_swaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_building_swaps_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_building_swaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_building_swaps_session_id'))

    op.drop_table('team_building_swaps')
    with op.batch_alter_table('draft_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_actions_session_id'))

    op.drop_table('draft_actions')
    with op.batch_alter_table('free_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_characters_season_id'))
        batch_op.drop_index(batch_op.f('ix_free_characters_character_id'))

    op.drop_table('free_characters')
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_sessions_room_code'))

    op.drop_table('draft_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('seasons')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_name'))

    op.drop_table('characters')
    # ### end Alembic commands ###
