"""add session persistence fields

Revision ID: 58a6820346e8
Revises: 52c1061bd345
Create Date: 2026-03-08 17:38:00.286955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a6820346e8'
down_revision: Union[str, None] = '52c1061bd345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('player_a_passed', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('player_b_passed', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.drop_column('player_b_passed')
        batch_op.drop_column('player_a_passed')
        batch_op.drop_column('is_paused')

    # ### end Alembic commands ###
