"""add_team_persistence_fields

Revision ID: a5ecd4cca187
Revises: 58a6820346e8
Create Date: 2026-03-08 20:21:04.787617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ecd4cca187'
down_revision: Union[str, None] = '58a6820346e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_a_team1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('player_a_team2', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('player_b_team1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('player_b_team2', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.drop_column('player_b_team2')
        batch_op.drop_column('player_b_team1')
        batch_op.drop_column('player_a_team2')
        batch_op.drop_column('player_a_team1')

    # ### end Alembic commands ###
