
"""Add icon_url and splash_art_url to Character

Revision ID: c37f72a562c2
Revises: 9523de22f708
Create Date: 2026-03-06 22:17:11

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c37f72a562c2'
down_revision: Union[str, None] = '9523de22f708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('splash_art_url', sa.String(length=500), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('splash_art_url')
        batch_op.drop_column('icon_url')

    # ### end Alembic commands ###
